/** Публичный API интерактивного редактирования (этап 29). */
export {
  EMPTY_SELECTION,
  activeId,
  boxContains,
  boxIntersects,
  childrenOf,
  clearSelection,
  extendSelection,
  furnitureOfPart,
  highlightedParts,
  isSelected,
  kindOf,
  normalizeBox3,
  parentOf,
  resolveClick,
  selectAll,
  selectChildren,
  selectInBox,
  selectParent,
  selectSingle,
  selectedParts,
  toggleSelection,
  type Box3,
  type SelectionEntry,
  type SelectionKind,
  type SelectionLevel,
  type SelectionState,
} from './selection';

export {
  DEFAULT_SNAP_3D,
  GRID_STEPS_3D,
  SNAP_PRIORITY,
  collectCandidates,
  describeSnap,
  faceCandidates,
  guideCandidates3D,
  partCandidates,
  snapAxis,
  snapPoint,
  snapPreview,
  snapRank,
  snapToGridValue,
  type Guide3D,
  type SnapAxis,
  type SnapCandidate3D,
  type SnapContext3D,
  type SnapKind3D,
  type SnapMatch,
  type SnapPoint,
  type SnapPointResult,
  type SnapPreview,
  type SnapSettings3D,
} from './snap';

export {
  DEFAULT_GIZMO,
  ROTATION_STEPS,
  constrainDelta,
  gizmoBounds,
  mirroredPosition,
  movedPosition,
  resizeHandles,
  rotatedRotation,
  type FlipAxis,
  type GizmoAxis,
  type GizmoBounds,
  type GizmoMode,
  type GizmoState,
  type ResizeHandle3D,
} from './gizmo';

export {
  DEFAULT_SIZE_LIMITS,
  checkSize,
  isPositionLocked,
  isSizeLocked,
  linkState,
  overriddenFields,
  resetToFormula,
  resizePart,
  resizePartTo,
  type LinkState,
  type ResizeOutcome,
  type ResizeRefusal,
  type SizeField,
  type SizeLimits,
} from './resize';

export {
  currentCoordinate,
  dragDivider,
  dragDoor,
  dragDrawer,
  dragShelf,
  dragTargetOf,
  indexOfPart,
  planPartDrag,
  type DragOutcome,
  type DragRefusal,
  type DragTarget,
  type PartDragPlan,
} from './drag';

export {
  anchorLength,
  beginDimensionEdit,
  cancelDimensionEdit,
  dimensionsOfPart,
  previewDimension,
  validateDimensionInput,
  type DimensionAnchor,
  type DimensionEdit,
  type DimensionKind,
  type DimensionPreview,
  type DimensionValidation,
  type LiveDimension,
} from './dimensions';

export {
  EMPTY_MEASURE,
  measureClick,
  measureDistance,
  measurePart,
  measurePoints,
  type MeasurePoint,
  type MeasureState,
  type Measurement,
  type PartMeasurement,
  type PartsDistance,
} from './measure';

export {
  COMMANDS,
  beginTransaction,
  commandsOfCategory,
  commitTransaction,
  findCommand,
  isCommandEnabled,
  rollbackTransaction,
  stepTransaction,
  type CommandCategory,
  type CommandDefinition,
  type Transaction,
  type TransactionKind,
} from './commands';

export {
  commandForKey,
  isTextInput,
  keyChord,
  shortcutList,
  type KeyEventLike,
  type TargetLike,
} from './shortcuts';

export {
  CABINET_MENU,
  EMPTY_MENU,
  PART_MENU,
  menuFor,
  type MenuItem,
} from './contextMenu';

export {
  LARGE_CHANGE_THRESHOLD,
  buildStatusLine,
  changePreview,
  dependencyPreview,
  formatMm,
  issuesByPart,
  linkIndicator,
  linkIndicators,
  type ChangePreview,
  type DependencyPreview,
  type LinkIndicator,
  type ObjectIssue,
  type StatusLine,
} from './status';
