/** Публичный API 2D-редактора конструкции. */
export {
  DEFAULT_EDITOR_2D,
  DEFAULT_SELECTION_FILTER,
  DEFAULT_SNAP,
  EMPTY_BOUNDS,
  GRID_STEPS_2D,
  type Bounds2D,
  type Dimension2D,
  type EditorEntity,
  type EditorTool,
  type Editor2DState,
  type EntityTransform,
  type EntityType,
  type Guide2D,
  type PendingOperation,
  type Rect2D,
  type ResizeHandle,
  type SelectionFilter,
  type SelectionState,
  type SnapSettings,
  type ViewPlane,
} from './types';

export {
  PLANE_AXES,
  boundsOf,
  cullEntities,
  fitBounds,
  planeAxisKeys,
  projectAABB,
  projectPoint,
  rectContains,
  rectIntersects,
  rectOf,
  screenToWorld,
  unprojectPoint,
  visibleBounds,
  worldToScreen,
  zoomAt,
  type Viewport,
} from './projection';

export {
  SYMBOL_SIZE,
  buildEntities,
  connectionEntities,
  edgeSymbols,
  findEntity,
  furnitureOfEntity,
  hardwareEntities,
  holeSymbols,
  modelOfEntity,
  moduleEntities,
  partEntities,
  partOfEntity,
  type BuildEntitiesOptions,
  type EdgeSymbol,
  type HoleSymbol,
} from './entities';

export {
  activeEntity,
  applyFilter,
  clearSelection,
  entityAt,
  markSelection,
  movableEntities,
  normalizeBounds,
  selectInRect,
  selectSingle,
  selectedEntities,
  selectionTypes,
  toggleSelection,
} from './selection';

export {
  distanceHints,
  extensionGuides,
  gapBetween,
  guideCandidates,
  objectCandidates,
  snapCoordinate,
  snapRect,
  snapValueToGrid,
  type DistanceHint,
  type SnapCandidate,
  type SnapContext,
  type SnapKind,
  type SnapResult,
} from './snap';

export {
  addGuide,
  clearGuides,
  createGuide,
  guideAt,
  guideId,
  guidesOfPlane,
  moveGuide,
  removeGuide,
  setGuideLocked,
} from './guides';

export {
  addDimension,
  boundingLabel,
  checkDimensionLink,
  createDimension,
  dimensionId,
  dimensionInfo,
  dimensionLength,
  dimensionOrientation,
  dimensionsOfPlane,
  parentOffsets,
  removeDimension,
  type BoundingLabel,
  type DimensionConflict,
  type DimensionInfo,
  type DimensionSource,
  type ParentOffsets,
} from './dimension';

export {
  addConstraint,
  anchorValue,
  constraintGlyph,
  constraintId,
  constraintStatus,
  createConstraint,
  isSatisfied,
  removeConstraint,
  setConstraintSuppressed,
  solveConstraints,
  targetFor,
  type Constraint2D,
  type ConstraintAnchor,
  type ConstraintGlyph,
  type ConstraintIssue,
  type ConstraintStatus,
  type ConstraintType,
  type SolveResult,
} from './constraints';

export {
  NUDGE_STEP,
  NUDGE_STEP_LARGE,
  alignEntities,
  centerInParent,
  distributeEntities,
  equalSize,
  nudgeDelta,
  translateEntities,
  type AlignMode,
  type PlacementPatch,
  type SizePatch,
} from './arrange';

export {
  MAX_DIMENSION,
  MIN_DIMENSION,
  ROTATIONS,
  entityExists,
  guardReadOnly,
  mirrorEntities,
  moveEntities,
  normalizeRotation,
  planeDeltaToWorld,
  resizeEntity,
  resizedRect,
  rotateEntities,
  setEntityPosition,
  setParameter,
  type ModelChange,
  type MirrorChange,
  type MoveChange,
  type OperationRefusal,
  type OperationResult,
  type ParameterChange,
  type ResizeOptions,
  type RotateChange,
} from './operations';

export {
  CLIPBOARD_FORMAT,
  CLIPBOARD_VERSION,
  PASTE_OFFSET,
  copyEntities,
  deleteImpact,
  isClipboardEmpty,
  pasteFurniture,
  pastePart,
  preparePaste,
  prepareDuplicate,
  readClipboard,
  writeClipboard,
  type ClipboardItem,
  type DeleteImpact,
  type EditorClipboard,
  type PasteResult,
} from './clipboard';

export {
  collectIssues,
  focusBounds,
  issueSummary,
  markStatuses,
  projectBounds,
  statusOfEntity,
  type EditorIssue,
  type IssueSeverity,
} from './validation';
